TextNotation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('txt_process.urls')),
    # path('doccano/', include('doccano.urls')),
    path('accounts/', include('django.contrib.auth.urls'))

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

txt_process/urls.py
from django.urls import path, include, re_path
from txt_process import views as txt_process_view

urlpatterns = [
    path("register/", txt_process_view.signup, name="register"),
    path('', txt_process_view.GetInfo.as_view(), name='home'),
    path('ducument/<int:pk>/', txt_process_view.DocumentDetail.as_view(), name='get_doc'),
    path('delet-ducument/<int:pk>/', txt_process_view.DocumentDelete.as_view(), name='delete_doc'),

    path('graph', txt_process_view.show_genres, name='graph'),
    # path('ee', txt_process_view.show_genres2, name='i'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('get-tree/<name>/', txt_process_view.TreeDetail.as_view(), name='get-tree'),
    # node do urls
    path('createNode/', txt_process_view.GenresDetail.as_view(), name='create_node'),

    path('setting/', txt_process_view.TreeListView.as_view(), name='setting'),

    #path('update-sentence/', txt_process_view.ParagraphDetail.as_view(), name='update-sentence'),
    re_path('edit-Sentence/(?P<pk>[0-9]+)/(?P<name>.*)/', txt_process_view.ParagraphDetail.as_view(), name='edit-sentence'),

    # path('edit-syntactic/', txt_process_view.ParagraphDetail.as_view(), name='edit-syntactic'),

    path('set-data-edit-syntactic/<int:pk>/<int:token_pk>/<slug:type>', txt_process_view.ParagraphSethDetail.as_view(), name='edit-syntactic-set-data'),

    path('set-data-edit-syntactic/', txt_process_view.ParagraphSethDetail.as_view(), name='edit-syntactic-set-data'),

    # get data for draw arc tree in sentence
    path('sentence-syntactic-tree-data/<int:pk>', txt_process_view.get_para_syntactic_tree_data,
         name='sentence-syntactic-tree-data'),

    path('delete-token-source-label/', txt_process_view.delete_token_source_label, name='delete-token-source-label'),

    path('morpho-analis/', txt_process_view.delete_token_source_label, name='delete-token-source-label'),

    path('token-edit/', txt_process_view.TokenDetail.as_view(), name='future-value-detail'),

    path('future-edit/', txt_process_view.FutureValueDetail.as_view(), name='future-value-detail'),

    path('future-edit/<int:pk>', txt_process_view.FutureValueDetail.as_view(), name='future-value-detail'),

    path('syntactic-edit/<int:pk>', txt_process_view.SyntacticDetail.as_view(), name='syntactic-detail'),

    path('create-file/<int:pk>', txt_process_view.download, name='create-file'),

    path('save-root/<int:pk>', txt_process_view.save_token_root, name='save_token_root'),

    path('new-sentence/<int:pk>', txt_process_view.edit_sentence, name='save_token_root'),

    path('get-sentence/', txt_process_view.get_sentence, name='get-sentence'),
]

txt_process/models.py
from django.db import models

# color field module
from colorfield.fields import ColorField

# tree module usage
from mptt.models import MPTTModel, TreeForeignKey

from django.conf import settings

User = settings.AUTH_USER_MODEL


class Document(models.Model):
    type_CHOICES = (
        ('F', 'فارسی'),
        ('I', 'آوانگاری شده'),
    )
    user = models.ForeignKey(User,
                             default=1,
                             null=True,
                             on_delete=models.SET_NULL
                             )
    name = models.CharField(max_length=255, blank=True)
    text = models.TextField(default=None)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=10, choices=type_CHOICES, blank=True, null=True)

    def __str__(self):
        return self.name


class Paragraph(models.Model):
    type_CHOICES = (
        ('F', 'فارسی'),
        ('I', 'آوانگاری شده'),
    )
    user = models.ForeignKey(User, default=1, null=True, on_delete=models.SET_NULL)
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    text = models.TextField(default=None
                            , blank=True)
    type = models.CharField(max_length=10, choices=type_CHOICES, blank=True, null=True)

    def __str__(self):
        return self.document.name


class Sentence(models.Model):
    type_CHOICES = (
        ('F', 'فارسی'),
        ('I', 'آوانگاری شده'),
    )
    user = models.ForeignKey(User, default=1, null=True, on_delete=models.SET_NULL)
    document = models.ForeignKey(Document, null=True, on_delete=models.CASCADE)
    paragraph = models.ForeignKey(Paragraph, null=True, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000, blank=True)
    type = models.CharField(max_length=10, choices=type_CHOICES, blank=True, null=True)

    def __str__(self):
        return self.text


class Genre(MPTTModel):
    type_CHOICES = (
        ('F', 'فارسی'),
        ('I', 'آوانگاری شده'),
    )

    name = models.CharField(max_length=50, unique=False,default='---' )
    futureFlag = models.BooleanField(default=False)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    color = ColorField(null=True, blank=True)
    type = models.CharField(max_length=10, choices=type_CHOICES, blank=True, null=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return self.name


class Token(models.Model):
    type_CHOICES = (
        ('F', 'فارسی'),
        ('I', 'آوانگاری شده'),
    )
    user = models.ForeignKey(User, default=1, null=True, on_delete=models.SET_NULL)
    document = models.ForeignKey(Document, null=True, on_delete=models.CASCADE)
    paragraph = models.ForeignKey(Paragraph, null=True, on_delete=models.CASCADE)
    sentence = models.ForeignKey(Sentence, on_delete=models.CASCADE)
    system_root = models.CharField(max_length=40, blank=True, default='---')
    user_root = models.CharField(max_length=40, blank=True)
    source = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
    target_label = models.ForeignKey(Genre, null=True, blank=True, on_delete=models.SET_NULL)
    tfidf = models.FloatField(default=1.6, blank=True)
    text = models.CharField(max_length=40, blank=True, default='---')
    bigPOS = models.ForeignKey(Genre, null=True, blank=True, on_delete=models.SET_NULL, related_name='big_ops')
    smallPOS = models.ForeignKey(Genre, null=True, blank=True, on_delete=models.SET_NULL, related_name='small_ops')
    type = models.CharField(max_length=10, choices=type_CHOICES, blank=True, null=True)

    class Meta:
        # order on primary key to make sure it's unique
        ordering = ['pk']


class FutureValue(models.Model):
    token = models.ForeignKey(Token, null=True, on_delete=models.CASCADE)
    future = models.ForeignKey(Genre, null=True, blank=True, on_delete=models.SET_NULL, related_name='future')
    futureValue = models.ForeignKey(Genre, null=True, blank=True, on_delete=models.SET_NULL, related_name='future_value')


class DocumentFile(models.Model):
    document = models.ForeignKey(Document, null=True, on_delete=models.CASCADE)
    file = models.FileField()


class TreeNode(models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

txt_process/views.py
import mimetypes
import os
import threading
from time import sleep
from wsgiref.util import FileWrapper

from django.conf import settings
from django.utils.encoding import smart_str
from next_prev import next_in_order, prev_in_order

from .forms import RegisterForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from mptt.templatetags.mptt_tags import cache_tree_children

from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from .serializers import (
    DocumentSerializer,
    DocumentModelSerializer,
    GenreModelSerializer)

from .my_hazm.Normalizer import Normalizer
from .my_hazm.SentenceTokenizer import SentenceTokenizer
from .my_hazm.WordTokenizer import WordTokenizer
from .my_hazm.Stemmer import Stemmer

from .models import (
    Document,
    Sentence,
    Paragraph,
    Token,
    Genre,
    FutureValue,
    DocumentFile
)

from .process import (
    recursive_node_to_dict,
    create_file,
    make_doc_file,

)
from rest_framework.decorators import api_view

from django.shortcuts import get_object_or_404

from django.views.generic.edit import DeleteView


class SyntacticDetail(LoginRequiredMixin, APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'txt_process/edit-syntactic.html'

    def get_object(self, pk):
        try:
            return Sentence.objects.get(pk=pk)
        except Document.DoesNotExist:
            raise Http404

    def get(self, request, pk):

        sentence = self.get_object(pk=pk)
        obj = get_object_or_404(Genre, name='????', parent=None)
        labels = obj.get_children()
        # leaf = obj.get_leafnodes()

        try:
            priv = Sentence.objects.filter(pk__lt=pk, document_id=sentence.document.pk).order_by('pk').last()
            # priv = prev_in_order(sentence, loop=True)
        except Exception as e:
            priv = None

        try:
            next = Sentence.objects.filter(pk__gt=pk, document_id=sentence.document.pk).order_by('pk').first()
            # next = next_in_order(sentence, loop=True)
        except Exception as e:
            next = None

        try:
            num = list(Sentence.objects.filter(document_id=sentence.document.pk).order_by('pk')).index(sentence) + 1
        except Exception as en:
            print(en)

        return Response({'sentence': sentence, 'type': 'syntactic', 'labels': labels, 'next': next, 'priv': priv, 'num': num})


class ParagraphDetail(LoginRequiredMixin, APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = 'txt_process/edit-sentence.html'

    def get_object(self, pk):
        try:
            return Sentence.objects.get(pk=pk)
        except Document.DoesNotExist:
            raise Http404

    def get(self, request, pk, name):

        global num
        sentence = self.get_object(pk=pk)
        obj = get_object_or_404(Genre, name=name, parent=None)
        leve_one = obj.get_children()
        leaf = obj.get_leafnodes()

        try:
            priv = Sentence.objects.filter(pk__lt=pk, document_id=sentence.document.pk).order_by('pk').last()
            # priv = prev_in_order(sentence)
        except Exception as e:
            priv = None

        try:
            next = Sentence.objects.filter(pk__gt=pk, document_id=sentence.document.pk).order_by('pk').first()
            # next = next_in_order(sentence)
        except Exception as e:
            next = None


        try:
            num = list(Sentence.objects.filter(document_id=sentence.document.pk).order_by('pk')).index(sentence) + 1
        except Exception as en:
            print(en)


        try:

            if name == 'صرفی':
                return Response(
                    {'leaf': leaf, 'sentence': sentence, 'level_one': leve_one, 'type': 'morpho', 'next': next,
                     'priv': priv, 'num': num})

            elif name == 'نحوی':
                return Response(
                    {'leaf': leaf, 'sentence': sentence, 'level_one': leve_one, 'type': 'syntactic', 'next': next,
                     'priv': priv})

        except Exception as e:
            print(e)

    def put(self, request, pk, name):

        sentence = get_object_or_404(Sentence, pk=pk)

        textNormal = Normalizer().normalize(text=request.data['text'])

        sentence.text = textNormal
        sentence.save()

        for token in sentence.token_set.all():
            token.delete()

        for tok in WordTokenizer().tokenize(textNormal):
            root_word = Stemmer().stem(tok)
            tok_obj = Token(user=request.user, document=sentence.document, system_root=root_word, paragraph=sentence.paragraph,
                            sentence=sentence, text=tok)
            tok_obj.save()

        return Response(status=status.HTTP_202_ACCEPTED, data={'ok': 'ok'})


class FutureValueDetail(LoginRequiredMixin, APIView):
    def get_object(self, pk):
        try:
            return FutureValue.objects.get(pk=pk)
        except Document.DoesNotExist:
            raise Http404

    def get(self, request, pk):

        obj = get_object_or_404(Genre, pk=pk)

        # childs = obj.get_children()
        # token = get_object_or_404(Token, pk=pk)

        childs = []
        for child in obj.get_children():
            childs.append({'name': child.name,
                           'pk': child.pk,
                           'future': child.futureFlag,
                           'tree_id': child.tree_id})

        return Response({'childs': childs})

    def post(self, request):

        obj = get_object_or_404(Genre, pk=request.data['future_pk'])
        # childs = obj.get_children()
        token = get_object_or_404(Token, pk=request.data['token_pk'])

        future = FutureValue(token_id=token.pk, future_id=obj.id)
        future.save()

        childs = []
        for child in obj.get_children():
            childs.append({'name': child.name,
                           'pk': child.pk,
                           'future': child.futureFlag,
                           'tree_id': child.tree_id,
                           'future_pk': future.pk})

        return Response({'childs': childs})

    def put(self, request):

        if request.data['type'] == 'FV':
            # future_obj = get_object_or_404(FutureValue,pk=request.data['future_pk'])
            obj = get_object_or_404(Genre, pk=request.data['future_value'])
            future_obj = FutureValue.objects.update_or_create(pk=request.data['future_pk'],
                                                              defaults={'futureValue_id': obj.pk})
        elif request.data['type'] == 'F':
            # future_obj = get_object_or_404(FutureValue,pk=request.data['future_pk'])
            obj = get_object_or_404(Genre, pk=request.data['future_node_pk'])
            token = get_object_or_404(Token, pk=request.data['token_pk'])
            future_obj = FutureValue.objects.update_or_create(pk=request.data['future_pk'],
                                                              defaults={'token_id': token.pk, 'future_id': obj.pk})

        childs = []
        for child in obj.get_children():
            childs.append({'name': child.name,
                           'pk': child.pk,
                           'future': child.futureFlag,
                           'tree_id': child.tree_id,
                           'future_pk': future_obj[0].pk})

        return Response({'childs': childs, 'future_pk': future_obj[0].pk})

    def delete(self, request):

        # print(1)

        if request.data['type'] == 'all':
            # print(2)
            token = FutureValue.objects.filter(token_id=request.data['token_pk'])
            for item in token:
                item.delete()
        elif request.data['type'] == 'one':
            obj = self.get_object(request.data['pk'])
            obj.delete()

        return Response(status=status.HTTP_204_NO_CONTENT)


class TokenDetail(LoginRequiredMixin, APIView):

    def get_object(self, pk):
        try:
            return Token.objects.get(pk=pk)
        except Document.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        pass

    def post(self, request):
        pass

    def put(self, request):
        try:
            if request.data['type'] == 'source&target':
                sentence_pk = None
                for path in request.data['data']:
                    try:
                        token = Token.objects.get(pk=path['target']['id'])
                        token.source = None
                        token.save()
                        sentence_pk = token.sentence.pk

                    except Exception as e:
                        print(e)

                return Response(status=status.HTTP_202_ACCEPTED, data={'sentence_pk': sentence_pk})
            elif request.data['type'] == 'smallPOS':
                token = self.get_object(request.data['token_pk'])
                token.smallPOS = None
                token.save()
                return Response(status=status.HTTP_202_ACCEPTED, data={'ok': 'ok'})
            elif request.data['type'] == 'bigPOS':
                token = self.get_object(request.data['token_pk'])
                token.bigPOS = None
                token.smallPOS = None
                token.save()
                return Response(status=status.HTTP_202_ACCEPTED, data={'ok': 'ok'})

        except Exception as e:
            print(e)
            return Response(status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request):
        pass


class ParagraphSethDetail(APIView):

    def get_object(self, pk):
        try:
            return Genre.objects.get(pk=pk)
        except Document.DoesNotExist:
            raise Http404

templates/txt_process/edit-syntactic.html
{% extends 'txt_process/text_base.html' %}
{% load static %}


{% block javascript %}

            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
            <script src="https://unpkg.com/bootstrap-table@1.15.4/dist/bootstrap-table.min.js"></script>

            <script src="https://d3js.org/d3.v4.min.js"></script>
            <script src="{% static 'txt_process/js/arcTree.js' %}"></script>
            <script src="{% static 'txt_process/js/syntactic_main.js' %}"></script>

            <script >
                $(document).ready(function() {
                  drawArcTree('sentence-syntactic-tree-data','{{ sentence.pk }}','card-body')
                });
            </script>



{% endblock %}

{% block css %}

    <link rel="stylesheet" href="{% static 'txt_process/css/edit-page.css' %}" />
    <link rel="stylesheet" href="{% static 'txt_process/css/arcTree.css' %}" />

{% endblock %}

{% block content %}

   <!-- Modal -->
    <div class="modal fade" id="modalSyntacticLabelPath" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header ">

                <button type="button" class="close shadow-none" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>

                  <h6 class="modal-title" id="exampleModalLongTitle"> کلمه مورد نظر را انتخاب کنید  </h6>
              </div>
              <div class="modal-body">


              <div class="row justify-content-between my-rtl px-4 mb-3 text-right" >
                {% for token in paragraph.token_set.all|dictsort:"pk"  %}
                   <button onclick="selectTargetTokenModal('{{ token.text }}', '{{ token.pk }}')" class=" btn btn-secondary text-white text-center m-1 p-1 rounded  " >  {{ token.text }}  </button>
                {% endfor %}
              </div>
              <div class="row justify-content-around" >
                  <div class="col-2 "><span id="modalSyntacticNodeTarget" ></span></div>
                  <div class="col-2" hidden ><span  id="modalSyntacticNodeTargetIdHidden" ></span></div>

                  <div class="col-4" >
                     <select id="modalSyntacticLabelSelectOption" class="form-control text-right">
                        {% for label in labels %}
                               <option style="color: {{ label.color }}" value="{{ label.pk }}" class="text-right">{{ label.name }}</option>
                        {% endfor %}
                     </select>
                  </div>


                  <div class="col-2" ><span  id="modalSyntacticNodeSource" ></span></div>
                  <div class="col-2" hidden ><span id="modalSyntacticNodeSourceIdHidden" ></span></div>
              </div>

              </div>
              <div class="modal-footer ">
                <button type="button" class="btn btn-secondary mx-2" data-dismiss="modal">بستن</button>
                <button type="button" onclick="saveSourceTargetTokenModal2('{{ sentence.pk }}')" class="btn btn-primary">ذخیره تغییرات</button>
              </div>
            </div>
          </div>
        </div>


    <div class="container">
        <div style="height: 85vh" class=" card  shadow-sm bg-white rounded">

            <div class="card-header">
                <div class="row" >
                     <div class="col-3 text-center mt-3">
                         {% if next %}
                             بعدی <a href="{% url 'syntactic-detail' pk=next.pk %}" ><i class="fa fa-arrow-circle-left text-info" ></i></a>

                             {% else %}
                             بعدی<a style="pointer-events: none" href="#" > <i class="fa fa-arrow-circle-left text-muted" ></i></a>
                         {% endif %}
                     </div>
                     <div class="col-6 text-center">
                         <div class="d-flex justify-content-around">
                             <div style="width: 45%" class="p-2 mt-2">{{ sentence.document.sentence_set.all|length }}</div>
                             <div style="width: 10%" class="p-2 mt-2"><label class=""> از </label> <label style="display: none" id="syntactic-sentence-pk">{{ sentence.pk }}</label></div>
                             <div style="width: 45%"  class="p-2"><input  type="number" id="syntactic-sentence-num" value="{{ num }}" class="form-control text-center shadow-none" /></div>
                         </div>
                     </div>
                     <div class="col-3 text-center mt-3">
                         {% if priv %}

                             <a href="{% url 'syntactic-detail' pk=priv.pk %}" > <i class="fa fa-arrow-circle-right text-info" ></i></a>قبلی

                             {% else %}

                             <a style="pointer-events: none" href="#" > <i class="fa fa-arrow-circle-right text-muted" ></i></a>قبلی
                         {% endif %}
                     </div>
                </div>
            </div>

        <div  class="card-body d-flex justify-content-center  p-0 {% if sentence.type == 'F' %} my-rtl {% endif %} " id="">

            <div class="p-2" id="card-body">

                <svg>  </svg>

            </div>

        </div>


        </div>
    </div>

{% endblock %}

templates/txt_process/genres.html
{% load static %}
{% load mptt_tags %}
<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="">
  <meta property="og:type" content="">
  <meta property="og:url" content="">
  <meta property="og:image" content="">


  <!-- Place favicon.ico in the root directory -->

  <link rel="stylesheet" href="{% static 'txt_process/css/normalize.css' %}">
  <link rel="stylesheet" href="{% static 'txt_process/css/main.css' %}">

  <link rel="stylesheet" href="{% static 'txt_process/css/foundation.css' %}" />
  <link rel="stylesheet" href="{% static 'txt_process/css/app.css' %}" />
  <link rel="stylesheet" href="{% static 'txt_process/css/d3-context-menu.css' %}" />

{#    <script src="https://ajax.googleapis.com/ajax/libs/d3js/6.1.1/d3.min.js"></script>#}
    <script src="{% static 'txt_process/js/d3.v3.min.js' %}"></script>
    <script src="{% static 'txt_process/js/d3-context-menu.js' %}"></script>
    <script src="{% static 'txt_process/js/underscore-min.js' %}"></script>
    <script src="{% static 'txt_process/js/jquery.js' %}"></script>
    <script src="{% static 'txt_process/js/fastclick.js' %}"></script>
    <script src="{% static 'txt_process/js/foundation.min.js' %}"></script>
    <script src="{% static 'txt_process/js/dndTree.js' %}"></script>

    <script src="{% static 'txt_process/js/main.js' %}"></script>





  <meta name="theme-color" content="#fafafa">
</head>

<body  >

           <div id="RenameNodeModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
          <h2 id="modalTitle">تغییر نام گره </h2>
          <form id="RenameNodeForm">
            <div class="row">
              <div class="large-12 columns">
                <label>نام گره
                  <input type="text" class="inputName" id='RenameNodeName' placeholder="node name" />
                </label>
              </div>
            </div>
            <div class="row">
              <div class="large-8 columns">
                &nbsp;
              </div>
              <div class="large-4 columns">
                <a href="#" class="button info" onclick="close_rename_node_modal()">لغو</a>
                <a href="#" class="button success" onclick="rename_node()">تغییر نام</a>
              </div>
            </div>
          </form>
          <a class="close-reveal-modal" aria-label="Close">&#215;</a>
        </div>

           <div id="CreateNodeModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
          <h2 id="modalTitle">ایجاد گره</h2>
          <form id="CreateNodeForm">
            <div class="row">
              <div class="large-12 columns">
                <label>نام گره
                  <input type="text" class="inputName" id='CreateNodeName' placeholder="node name" />
                </label>
              </div>
            </div>
            <div class="row">
              <div class="large-8 columns">
                &nbsp;
              </div>
              <div class="large-4 columns">
                <a href="#" class="button info" onclick="close_create_node_modal()">لغو</a>
                <a href="#" class="button success" onclick="create_node()">ایجاد</a>
              </div>
            </div>
          </form>
          <a class="close-reveal-modal" aria-label="Close">&#215;</a>
        </div>



        <div class="align-content-center" id="tree-container"></div>

  <script src="{% static 'txt_process/js/vendor/modernizr-3.11.2.min.js' %}"></script>
  <script src="{% static 'txt_process/js/plugins.js' %}"></script>


  <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto'); ga('set', 'anonymizeIp', true); ga('set', 'transport', 'beacon'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async></script>
</body>

</html>

templates/txt_process/text_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>


<link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css" integrity="sha384-vus3nQHTD+5mpDiZ4rkEPlnkcyTP+49BhJ4wJeJunw06ZAp+wzzeBPUXr42fi8If" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'txt_process/css/txt_process.css' %}" >

    {% block css %}

    {% endblock %}


</head>

<body class="bg-secondary">

 <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2 ">
      <a class="navbar-brand" href="{% url 'setting' %}"><i class="fa fa-cog text-warning" ></i></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto  ">

          {% if user.is_authenticated %}

                <li class="nav-item active">
                  <a class="nav-link  " href="{% url 'logout'%}?next={{request.path}}" > {{ user.get_username }} <i class="fa fa-sign-out text-warning" > </i>  </a>
                </li>

           {% else %}

                <li class="nav-item active">
                  <a class="nav-link " href="{% url 'login'%}?next={{request.path}}" ><i class="fa fa-sign-in text-warning" ></i> {{ user.get_username }}  </a>
                </li>

           {% endif %}

           <li class="nav-item active">
            <a class="nav-link " href="{% url 'home' %}" ><i class="fa fa-home text-warning" ></i> </a>
          </li>
        </ul>

      </div>
    </nav>


{% block content %}

{% endblock %}
<script src="{% static 'txt_process/js/jquery.js' %}"></script>
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js" integrity="sha384-a9xOd0rz8w0J8zqj1qJic7GPFfyMfoiuDjC9rqXlVOcGO/dmRqzMn34gZYDTel8k" crossorigin="anonymous"></script>
{#<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>#}
    {% block javascript %}

    {% endblock %}

</body>
</html>